aggregator:
  topic:
    telemetry-snapshots: telemetry.snapshots.v1

topic:
  telemetry-sensors: telemetry.sensors.v1

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: serializer.SerializerAvro

    consumer:
      client-id: SensorEventConsumer
      group-id: sensorEvent.group.id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: deserializer.SensorEventDeserializer
      enable-auto-commit: false
